### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nkdiep24** [OneSignal/OneSignal-DotNet-SDK#100]
### What happened?

When i try to install the package via NUGET it face this error and can't install 
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find a part of the path 'C:\Users\React Kien\.nuget\packages\onesignalsdk.dotnet\5.1.1\res\ios\OneSignalFramework.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalFramework.framework\Versions\Current\Modules\OneSignalFramework.swiftmodule\x86_64-apple-ios-macabi.private.swiftinterface'.				

### Steps to reproduce?

```Markdown
1. just run Install-Package OneSignalSDK.DotNet -Version 5.1.1 in Visual Studio 2022
2. then it turn out error
```

### What did you expect to happen?

Just to install it successfully

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jomargon** [comment]
I was able to get past this by not installing the Nuget package using Visual Studio and instead using `dotnet add package OneSignalSDK.DotNet`

**Comment by nkdiep24** [comment]
> I was able to get past this by not installing the Nuget package using Visual Studio and instead using `dotnet add package OneSignalSDK.DotNet`

Thank you. You made my day !

**Comment by SelmanGedik** [comment]
I'm having this problem and unfortunately I can't solve it with PowerShell, can you help me?
