### ISSUE TITLE
[Bug]: Missing dSYM / DWARF on iOS release warning

### ISSUE THREAD

**Issue by alexsmi-noveo** [OneSignal/OneSignal-DotNet-SDK#124]
### What happened?

Releasing iOS app with OneSignal SDK v5.2.1 i got warning about missing DWARF file for OneSignal framework. Overall AppStore allows me to upload. But this warning didn't exist until Xcode v16.

MAUI v8.0.92
NET SDK 8.0.403
OneSignal v5.2.1
XCode v16

![image](https://github.com/user-attachments/assets/030cd92d-9a0a-4fb5-88c7-2f974886bfea)

### Steps to reproduce?

```Markdown
1. Create app and including OneSignal from nuget.
2. Select iOS target. Create required provisioning profile. Release an archive.
3. Open Xcode -> Window -> Organizer.
4. Select App archive, then validate or Distribute command in the right pane.
5. Get warning from AppStore.
```

### What did you expect to happen?

Release without warnings

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @alexsmi-noveo thanks for reporting.

This is a new warning as of Xcode 16 and can be safely ignored. 

To omit the warning, you can follow the suggestion from this Apple thread: https://forums.developer.apple.com/forums/thread/763731

![Screenshot 2024-10-23 at 11 57 06 AM](https://github.com/user-attachments/assets/5a2dfe99-7e55-45c4-99c6-eeb5aa6ef06e)
