### ISSUE TITLE
Request to use the nuget for net7 aswell

### ISSUE THREAD

**Issue by taz4270** [OneSignal/OneSignal-DotNet-SDK#17]
### How can we help?

Hi,
Can you put the package available for net7, net7-android and net7-ios aswell as net6 plz?
Maui is available for net7 now

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @taz4270 sorry for the delay!  Even though the library targets net6 I have confirmed it can be used by a net7 project.  Can you please let me know what specific error message you might be having and we can try to reproduce it?  Thanks so much!

**Comment by taz4270** [comment]
I kinda forgot about this too xD
I already tested but forgot to say anything
I only said that so no one get confused with a "well its net6, its not available to net7 yet"
