### ISSUE TITLE
[Bug]: ITMS-90482: Invalid Executable OneSignal contains bitcode

### ISSUE THREAD

**Issue by michelsoftware** [OneSignal/OneSignal-DotNet-SDK#27]
### What happened?

I've tested this in version OneSignalSDK.DotNet  4.3.0 and 4.3.1.

When sending the IPA to the App store it's rejected and I get the following message:

We identified one or more issues with a recent delivery for your app, "*******". Please correct the following issues, then upload again. 
ITMS-90482: Invalid Executable - The executable 'BiblioNext.Ui.Ebieb.app/Frameworks/OneSignal.framework/OneSignal' contains bitcode. 
ITMS-90482: Invalid Executable - The executable 'BiblioNext.Ui.Ebieb.app/Frameworks/OneSignalCore.framework/OneSignalCore' contains bitcode. 
ITMS-90482: Invalid Executable - The executable 'BiblioNext.Ui.Ebieb.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' contains bitcode. 
ITMS-90482: Invalid Executable - The executable 'BiblioNext.Ui.Ebieb.app/Frameworks/OneSignalOutcomes.framework/OneSignalOutcomes' contains bitcode

### Steps to reproduce?

```Markdown
1. Install OneSignalSDK.DotNet  4.3.1.
2. Create the App
3. Send to Apple App Store
4. Recieve email with above error message
```

### What did you expect to happen?

Apple Store should accept new version. It seems that they don't accept bitcode since Xcode 14.0 anymore

### Relevant log output

```Shell
We identified one or more issues with a recent delivery for your app, "eBieb" 3.3.1 (22122910). Please correct the following issues, then upload again. 
ITMS-90482: Invalid Executable - The executable 'BiblioNext.Ui.Ebieb.app/Frameworks/OneSignal.framework/OneSignal' contains bitcode. 
ITMS-90482: Invalid Executable - The executable 'BiblioNext.Ui.Ebieb.app/Frameworks/OneSignalCore.framework/OneSignalCore' contains bitcode. 
ITMS-90482: Invalid Executable - The executable 'BiblioNext.Ui.Ebieb.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' contains bitcode. 
ITMS-90482: Invalid Executable - The executable 'BiblioNext.Ui.Ebieb.app/Frameworks/OneSignalOutcomes.framework/OneSignalOutcomes' contains bitcode
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @michelsoftware .  We experienced this same issue with our [unity SDK](https://github.com/OneSignal/OneSignal-Unity-SDK/pull/546) , the solution there was to upgrade XCode.  Can you please let me know if this resolves your issue?

**Comment by brismithers** [comment]
I also found this [maui issue](https://github.com/dotnet/maui/issues/10989#issuecomment-1304317816) as a potential workaround, as we try to better understand the path forward.

**Comment by brismithers** [comment]
@michelsoftware I've confirmed the fix described [here](https://github.com/dotnet/maui/issues/10989#issuecomment-1304317816) does address the issue as a workaround.  We will see if there can be a more permanent fix for this. thanks!

**Comment by michelsoftware** [comment]
Hi Brismithers, thank you for helping out. I've tested the workaround and it works fine.
