### ISSUE TITLE
[Looking for Feedback] OneSignal SDK v5.0.0-beta02 Released! 

### ISSUE THREAD

**Issue by brismithers** [OneSignal/OneSignal-DotNet-SDK#42]
### What's on your mind?

In this major version beta release for the OneSignal SDK, we are making a significant shift from a device-centered model to a user-centered model.  A user-centered model allows for more powerful omni-channel integrations within the OneSignal platform.

For information please see the [migration guide](https://github.com/OneSignal/OneSignal-DotNet-SDK/blob/5.0.0-beta01/MIGRATION_GUIDE.md).

🚧 **Beta release. It is not recommended to use in production.** 🚧

Please post any feedback related to the alpha under this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by T-T-P** [comment]
Not sure if of use to you guys but I tried to install this to my MAUI project (both as new nuget and as an upgrade from 4.3.3) and I receive the following error:

Could not find a part of the path 'C:\Users\Admin\.nuget\packages\onesignalsdk.dotnet\5.0.0-beta01\res\ios\OneSignalFramework.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalFramework.framework\Versions\Current\Modules\OneSignalFramework.swiftmodule\x86_64-apple-ios-macabi.private.swiftinterface'.

If you need any further information please let me know and I'll try to help further.

**Comment by brismithers** [comment]
@T-T-P thanks for checking out the beta!  I've checked the package and it looks like that path does exist within the package, can you confirm the path exists on your file system?  If it does, I think you might be running up against a max path length issue.

**Comment by brismithers** [comment]
The v5.0.0-beta02 has been released. For more information please see the [migration guide](https://github.com/OneSignal/OneSignal-DotNet-SDK/blob/5.0.0-beta02/MIGRATION_GUIDE.md).

**Comment by T-T-P** [comment]
@brismithers Thank you for your swift response, I have also now had a chance to try v5.0.0-beta02 and I'm afraid I run in to the same error with that:

Could not find a part of the path 'C:\Users\Admin\.nuget\packages\onesignalsdk.dotnet\5.0.0-beta02\res\ios\OneSignalFramework.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalFramework.framework\Versions\Current\Modules\OneSignalFramework.swiftmodule\x86_64-apple-ios-macabi.private.swiftinterface'.				

I have checked the folder C:\Users\Admin\.nuget\packages\onesignalsdk.dotnet\5.0.0-beta02\res\ios\OneSignalFramework.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalFramework.framework\Versions\Current\Modules\OneSignalFramework.swiftmodule\ and it is in fact empty so the file x86_64-apple-ios-macabi.private.swiftinterface doesn't exist there for some reason?

It could be a max path issue preventing the file be created, but with the username "Admin" the path couldn't be too much smaller so I would expect more testers to have the same issue?

Obviously being a beta it's not a big problem for me atm but it would be nice to test some of the new features of v5.0.0 within MAUI ;-)

**Comment by T-T-P** [comment]
Hi Guys,

So the above is still a problem in the latest beta (5.0.0-beta03 on Windows) however I have been able to install and test it on a Mac and it runs perfectly, everything seems to work in both Debug & Release mode on iOS & Android which is great!

I have a quick request for the next beta, would it be possible to change the nuget package to support .net 8 too as it currently only supports .net 7 and I would like to run some tests in the latest MAUI pre release (which is .net 8) if possible?

Keep up the great work and thank you guys :-)

**Comment by realchrisparker** [comment]
Hello,

I get this as well.

Could not find a part of the path 'C:\Users\parke\.nuget\packages\onesignalsdk.dotnet\5.0.0-beta03\res\ios\OneSignalFramework.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalFramework.framework\Versions\Current\Modules\OneSignalFramework.swiftmodule\x86_64-apple-ios-macabi.private.swiftinterface'.

**Comment by Dipannita20** [comment]
Hello,

I am also getting same error, also check the path there is no file x86_64-apple-ios-macabi.private.swiftinterface, I am on windows system. x86_64-apple-ios-macabi.private.swiftinterface file is missing. 

![image](https://github.com/OneSignal/OneSignal-DotNet-SDK/assets/68427594/1a55dd84-a083-4113-9075-eb4f5efb6ff4)

**Comment by palanikumar32** [comment]
For me too, Nuget throws below error while updating package from 4.33 to 5.0.0

`Error		Could not find a part of the path 'C:\Users\palanikumar\.nuget\packages\onesignalsdk.dotnet\5.0.0\res\ios\OneSignalFramework.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalFramework.framework\Versions\Current\Modules\OneSignalFramework.swiftmodule\x86_64-apple-ios-macabi.private.swiftinterface'.	`

Downloaded the package manually and compare with nuget cache location, lot of files were missing. It can't be fixed even if i copy those files, nuget roll backed the copied files.

![image](https://github.com/OneSignal/OneSignal-DotNet-SDK/assets/11205970/c14d5df5-6858-4be9-a2eb-739722b48b84)

**Comment by Dipannita20** [comment]
resolved this by creating NuGet.Config in the root of solution folder and specified the path as c:\nuget
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<config>
		<add key="globalPackagesFolder" value="c:\nuget" />
	</config>
</configuration>
`

**Comment by palanikumar32** [comment]
> resolved this by creating NuGet.Config in the root of solution folder and specified the path as c:\nuget `<?xml version="1.0" encoding="utf-8"?> <configuration> <config> <add key="globalPackagesFolder" value="c:\nuget" /> </config> </configuration> `

It is working fine...!

**Comment by pierrebrito** [comment]
Version 5.0.2 still has a reference error.

<img width="814" alt="Screenshot_1" src="https://github.com/OneSignal/OneSignal-DotNet-SDK/assets/6466875/87ca72e0-a560-4673-8274-b6f845c1a116">

**Comment by T-T-P** [comment]
Why has this been closed when multiple of us have reported issues that persist even in v5.0.x release versions?

**Comment by grabnerM** [comment]
I don´t know if I am the only user but this is still a problem for me. Since VS for Mac is running out I have to switch to Rider or VSCode. Currently I am testing Rider but I could not get it running there. 
So i tried it on my Windows machine and getting this error. The workaround from @Dipannita20 is nice but can´t be the solution for this. 
We are a bigger App-Team and not a one-man team. For me its not possible to be the first level support for my colleagues to get the app running because one specific nuget package wont load..

**Comment by it11111111** [comment]
This is still an issue for me as well. when upgrading versions or even installing from scratch. I am on Visual Studio for WIndows
