### ISSUE TITLE
[Bug]: MAUI - OneSignal not working at all on iOS

### ISSUE THREAD

**Issue by whoteit** [OneSignal/OneSignal-DotNet-SDK#53]
### What happened?

First time OneSignal user. We create a .NET MAUI app targeting .NET 7.0 and followed the .NET guide to the letter.
https://documentation.onesignal.com/docs/net-sdk-setup

Everything works perfectly on Android, but nothing works on iOS. We call OneSignal.Default.Initialize(...) followed by PromptForPushNotificationsWithUserResponse, and nothing happens. No exceptions, no errors, and the device does not appear in the users list in the dashboard.

I set logs to verbose as follows : 
OneSignal.Default.LogLevel = LogLevel.VERBOSE;
OneSignal.Default.AlertLevel = LogLevel.NONE;

... and yet nothing related to OneSignal is output to the debug window in Visual Studio when running on my iPhone. The logs work fine when debugging on Android (both emulator and physical device).

### Steps to reproduce?

```Markdown
1. Create .NET MAUI app targeting .NET 7.0
2. Reference OneSignal nuget (<PackageReference Include="OneSignalSDK.DotNet" Version="4.3.3" />)
3. Add following code to App.xaml.cs
``OneSignal.Default.Initialize("...");
OneSignal.Default.PromptForPushNotificationsWithUserResponse();
OneSignal.Default.PushEnabled = true;``
4. Go to OneSignal dashboard. iPhone devices does not appear. All Android devices appear just fine.
```

### What did you expect to happen?

Push notifications should work
iPhone user should appear in the users list in the dashboard

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by whoteit** [comment]
No change unfortunately. Deleted obj / bin and rebuilt solution, still see nothing in the debug output related to OneSignal and notifications don't work / user doesn't appear in the Users list.

I am doing nothing special. This is the code of my App() constructor (App.xaml.cs)
```
        OneSignal.Default.LogLevel = LogLevel.VERBOSE;
        OneSignal.Default.AlertLevel = LogLevel.NONE;

        var promotionsAllowed = Preferences.Default.Get("promotions_allowed", true);

        if (promotionsAllowed)
        {
            OneSignal.Default.Initialize("...");
                
            OneSignal.Default.PushEnabled = true;
        }
```

**Comment by whoteit** [comment]
@brismithers do you think this is due to me deploying a debug version to my iPhone (using VS hot-restart, without a paired mac or xcode) ?

**Comment by Driloncpp** [comment]
Hello everyone. Looks like you have the same problem as I have. Did you find any solution or fix for this problem?

**Comment by whoteit** [comment]
Hello, yes. It turns out it doesn't work when deploying the app to iOS directly from Visual Studio (hot restart). It works fine without any changes when Visual Studio is paired with a Mac + XCode.

**Comment by Driloncpp** [comment]
What do you exactly mean with paired with a Mac + XCode? do I have to deploy it from a Mac to my device? Is there a documentation about it?

**Comment by whoteit** [comment]
Yes, https://learn.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac

Then when debugging in VS, chose iOS remote devices, and your iPhone (physically connected to your Mac) should appear there.

**Comment by douglassimaodev** [comment]
OneSignal.Default... where is "Default"  it is not longer in there

**Comment by grabnerM** [comment]
@douglassimaodev Same here.. Did you find a solution for this problem?

**Comment by emawby** [comment]
@grabnerM Hello Default has been removed since the beta versions of the SDK so you should be able to access the other namespaces directly. If you are not able to please let me know.

**Comment by Marioo1357** [comment]
Still not works, any leftovers?
Even fiddler do not catch any http request leaving app

**Comment by nan-li** [comment]
Hi, we have had no further reports of this. If this is still an issue, please open a new report with updated information.
