### ISSUE TITLE
[Bug]: MAUI Windows App

### ISSUE THREAD

**Issue by Sen-Gupta** [OneSignal/OneSignal-DotNet-SDK#56]
### What happened?

Assuming Multi-platform App UI and other .NET applications supports windows?

The MAUI Windows App on .Net 7 on Visual Studio throws un-implemented exception.
![image](https://user-images.githubusercontent.com/8068582/232194232-16b8ea87-3744-4f90-a978-a46fdfabf0db.png)

In the output windows, we can see it shows NotImplementedException. (We don't have support for Windows?)

### Steps to reproduce?

```Markdown
1) Create a brand new MAUI Project
2) Follow Steps to integrated .Net Core SDK provided on OneSignal (https://documentation.onesignal.com/docs/net-sdk-setup)
3) Run Windows Project for MAUI
4) You will encounter the error 
Exception thrown: 'System.NotImplementedException' in OneSignalSDK.DotNet.dll
```

### What did you expect to happen?

1) If it supports windows, it should work
else
2) Provide guidance on what is requried to avoid the error

### Relevant log output

```Shell
'PartnersBlazorMaui.exe' (CoreCLR: clrhost): Loaded 'D:\AaryaRepos\AaryaOnDapr\src\NativeApps\PartnersBlazorMaui\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\OneSignalSDK.DotNet.dll'. 
'PartnersBlazorMaui.exe' (CoreCLR: clrhost): Loaded 'D:\AaryaRepos\AaryaOnDapr\src\NativeApps\PartnersBlazorMaui\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\OneSignalSDK.DotNet.Core.dll'. 
'PartnersBlazorMaui.exe' (CoreCLR: clrhost): Loaded 'D:\AaryaRepos\AaryaOnDapr\src\NativeApps\PartnersBlazorMaui\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.Loader.dll'. 
Exception thrown: 'System.NotImplementedException' in OneSignalSDK.DotNet.dll
'PartnersBlazorMaui.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Sorry for the late response but, we don’t have support for Windows
