### ISSUE TITLE
[question]: Notification Service Extension

### ISSUE THREAD

**Issue by MingK12** [OneSignal/OneSignal-DotNet-SDK#61]
### How can we help?

How do I can put the onesignal extention on the maui shared project (iOS and Android)
![image](https://github.com/OneSignal/OneSignal-DotNet-SDK/assets/121235465/f9153df2-d211-4657-b7d4-3b5f1c9d48b1)(1)
I tried but i allways get this error
![image](https://github.com/OneSignal/OneSignal-DotNet-SDK/assets/121235465/09c1d4be-934c-4382-b945-8e3b22325238)
Or exists outher than this extention (1) ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@MingK12 I apologize for the late response were you able to resolve this issue? Creating Notification Service Extensions in Maui projects was not well supported with older versions of Visual Studio for mac. I believe it was updated to add support for this

**Comment by emawby** [comment]
closing
