### ISSUE TITLE
[Bug]: Cannot install OneSignalSDK.DotNet Maui

### ISSUE THREAD

**Issue by gabsamples6** [OneSignal/OneSignal-DotNet-SDK#65]
### What happened?

We are upgrading from Xamarin to Maui and installing the OneSignalSDK.DotNet causes an error

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\anyUser\.nuget\packages\onesignalsdk.dotnet\5.0.0\res\ios\OneSignalFramework.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalFramework.framework\Versions\A\Modules\OneSignalFramework.swiftmodule\x86_64-apple-ios-macabi.private.swiftinterface'.

### Steps to reproduce?

```Markdown
Create A maui app .net 7 or 8 (windows pc)
Go to nuget packages and install OneSignalSDK.DotNet
See
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\anyUser\.nuget\packages\onesignalsdk.dotnet\5.0.0\res\ios\OneSignalFramework.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalFramework.framework\Versions\A\Modules\OneSignalFramework.swiftmodule\x86_64-apple-ios-macabi.private.swiftinterface'.
```

### What did you expect to happen?

I expected to install the nuget successfully

Does OneSignal support Maui?

many thanks

### Relevant log output

```Shell
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\anyUser\.nuget\packages\onesignalsdk.dotnet\5.0.0\res\ios\OneSignalFramework.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalFramework.framework\Versions\A\Modules\OneSignalFramework.swiftmodule\x86_64-apple-ios-macabi.private.swiftinterface'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gabsamples6** [comment]
Is anyone monitoring this issues?

**Comment by TedMobile** [comment]
I get the same error when installing on a blank maui app .net 7 or 8

**Comment by gabsamples6** [comment]
I close this issue because this is todo with xamarin.ios not handling long path

**Comment by nkdiep24** [comment]
@gabsamples6 can i know how to solve it? i'm using latest version also can't install via nuget
