### ISSUE TITLE
[question]: Problem version 5.0.0 in IOS 17 with xcode15

### ISSUE THREAD

**Issue by skyangel78** [OneSignal/OneSignal-DotNet-SDK#66]
### How can we help?

Hi OnesignaSDk.DotNet fuction with XCode 15 and IOS 17?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Yes, the SDK should work with Xcode 15 and iOS 17

What issues are you seeing?

**Comment by dmm-l-mediehus** [comment]
I have same issue on Xcode 15 and running on simulator 'iPhone 15 iOS 17', but I'mn using OneSignalSDK.DotNet nuget package version 5.0.2 (latest as of now), error:

![Skærmbillede 2023-10-26 113438](https://github.com/OneSignal/OneSignal-DotNet-SDK/assets/125255354/478ccf54-4c31-4935-8f81-fcf64c8de3b9)

**Comment by emawby** [comment]
@dmm-l-mediehus Tracking this in number #76 closing this one since they appear to be the same error
