### ISSUE TITLE
[question]:Is onesignal dot net dead?

### ISSUE THREAD

**Issue by developer9969** [OneSignal/OneSignal-DotNet-SDK#69]
### How can we help?

Hi
One signal seems to be one of the leading provider in the field , however when it comes to .net , there is hardly any support.

Is this nuget dead? iOS does not work at all and questions there seems to be just forgotten.

Hey - onesignal are you there?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
We are still supporting the OneSignal-DotNet-SDK

What issues are you seeing on iOS?
We published a new [5.0.2](https://github.com/OneSignal/OneSignal-DotNet-SDK/releases/tag/5.0.2) release to fix iOS builds, let us know if you're still having issues

**Comment by developer9969** [comment]
@shepherd-l thanks for the update.I will try the latest build.we are evaluating Onesignal for our Maui priojects but we are concerned by the lack of response or very delayed responses on people questions. Does paid version get a different response time?

**Comment by shepherd-l** [comment]
We try our best to respond to everyone promptly and are urgently working through issues with the 5.0.0 version.

Any issues raised on GitHub across all SDKs are handled by the SDK team.

We have a customer support team and dedicated services available. You can contact the support team on our website: https://onesignal.com/contact

Customer Support plans are listed [here](https://onesignal.com/pricing) under “Customer Support”

**Comment by TedMobile** [comment]
@shepherd-l  the point I was making is that for 3 or more weeks there was total radio silence on issues that are showstoppers, and as a business is worrying , if something goes wrong , we need acknowledgment and feedback -  

I hope you understand where I am coming from .  Regarding support if I am on a paid plan will this issue be looked at immediately as opposed to a free plan?

**Comment by emawby** [comment]
@TedMobile We do understand your frustration and are working to respond to Github issues promptly. The level of support plan does not affect the speed that we address these issues on Github.
