### ISSUE TITLE
Closed: Issue Resolved

### ISSUE THREAD

**Issue by T-T-P** [OneSignal/OneSignal-DotNet-SDK#75]

**Comment by T-T-P** [comment]
@brismithers @brayden-onesignal Is this something that the OneSignal team could look into please? Many thanks in advance.

**Comment by imran470** [comment]
how to resolve this issue? [Bug]: ANR [libc.so] __futex_wait_ex(void volatile*, bool, int, bool, timespec const*)

**Comment by jackteng9725** [comment]
I also encountered this problem, how to solve it?
ANR  [libc.so] __futex_wait_ex(void volatile*, bool, int, bool, timespec const*)
