### ISSUE TITLE
[question]: How to set ExtenralIds if IncludeExternalUserIds is deprecated for push notifications

### ISSUE THREAD

**Issue by Nathanrawson** [OneSignal/OneSignal-DotNet-SDK#80]
### How can we help?

Hi, in the SDK it says IncludeExternalUserIds is deprecated, however if I set the IncludeAliases label instead, where do I set the externalUserIds. I can't seem to find any documentation on this. Would really appreciate the help

            StringMap contents = new StringMap { En = "This is a new .net test" };
            PlayerNotificationTargetIncludeAliases externalIds = new PlayerNotificationTargetIncludeAliases
            {
                AliasLabel = new List<string> { "external_Id" },

            };
           
            var notification = new Notification(appId: "myAppid")
            {
               Contents = contents,
               IncludeAliases =externalIds,
                TargetChannel = Notification.TargetChannelEnum.Push,
                Headings = new StringMap {En = "message"},
               
            };

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
This is currently a known bug. As a workaround for now, you can continue to use IncludeExternalUserIds even though it's marked as deprecated

Closing due to duplicate issue here: https://github.com/OneSignal/onesignal-dotnet-api/issues/34
