### ISSUE TITLE
[question]: How do I retrieve a users current tags?

### ISSUE THREAD

**Issue by matthewrdev** [OneSignal/OneSignal-DotNet-SDK#85]
### How can we help?

As per title.

In previous implementations of the OneSignal Xamarin SDK, I could invoke the following code to retrieve the tags for a given user:

```
var myTags = await OneSignal.Default.GetTags();
```

However, in the current OneSignalSDK.DotNet nuget package (5.0.2), I cannot see an equivalent method. 

In this repository I can see that the `OneSignalSDK.DotNet.OneSignal` class has a method [CreateOneSignal](https://github.com/OneSignal/OneSignal-DotNet-SDK/blob/5254d47220b3f8c7057d801c8a0754e5caa468cb/OneSignalSDK.dotnet/OneSignalSDK.DotNet.cs#L22) which creates a platform specific OneSignalSDKInternal which implements a `GetTags` method.

This is my IntelliSense view for the `OneSignalSDK.DotNet.OneSignal`  APIS:

<img width="396" alt="onesignal-1" src="https://github.com/OneSignal/OneSignal-DotNet-SDK/assets/3260473/a921e807-ad92-4e84-83a1-c331a8fe3af6">
<img width="395" alt="onesignal-2" src="https://github.com/OneSignal/OneSignal-DotNet-SDK/assets/3260473/58f3afe0-4fe3-4826-8ed8-016f436404a0">

And when I have used dotPeek to inspect the DLLs bundled into the MAUI app, dotPeek does not show any references to `OneSignalSDKInternal`.

Am I missing a NuGet reference? How can I get access to the GetTags method?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
We are in the process of adding GetTags to 5.x and it should be available in the next release. (We have a PR up for it here: https://github.com/OneSignal/OneSignal-DotNet-SDK/pull/84)

**Comment by matthewrdev** [comment]
@shepherd-l Thanks for following up and great to see there was already a PR. 🎉

Is there an ETA on when this feature will be released? We have a few apps in the final steps of a MAUI conversion and this was one of the final pieces.

**Comment by shepherd-l** [comment]
@matthewrdev
We plan to get a release out next week

**Comment by emawby** [comment]
This is available in the 5.1.0 version
